- CHANGELOG.md
- README.md
- lib/src/drawings.dart
- test/drawing_test.dart
You can now specify the color in which the icon should be drawn. If it is not specified or if the specified color is badly formatted, the icon will be drawn in black.
> Add a color parameter to IconDrawing

- CHANGELOG.md
- README.md
- lib/src/drawings.dart
In the future versions of the firmware, it will be possible to choose the color and the size of a text. To help developers to prepare this feature, the API has been completed with these two parameters. However, do not be surprised that it does not impact the color or the size of the element on the aRdent glasses.
> [ADD] Add size and color parameter to TextDrawing

- CHANGELOG.md
- README.md
- example/example.dart
- lib/flutter_gyw.dart
- lib/src/drawings.dart
- pubspec.yaml
- test/drawing_test.dart
This PR adds the possibility to change the background color of the screen.
To do so,  `WhiteScreen` objects are replaced by `BlankScreen` with a color parameter. This parameter (optional) describes the color to use as background. If not specified, it remains the same as before.
Note : This feature will only work from firmware 1.1.5
> Convert WhiteScreen into BlankScreen with a color parameter 

- CHANGELOG.md
- README.md
- lib/src/drawings.dart
Some use cases require custom icons that are not necessarily part of the library. Before this change, theses custom icons blocked the entire deserialization process. They are now supported, and the icon will be sent correctly to the glasses.
This change also fixes the problem of an app that is not synchronous with the last icon library updates.
> Support custom icons

- CHANGELOG.md
- lib/src/bt_device.dart
- lib/src/drawings.dart
`TextDrawing` can be used to specify the font size and color, and now it also sends these properties to the device through Bluetooth.
> Deprecate the set font command

- .github/workflows/lint_tests.yml
- CHANGELOG.md
- analysis_options.yaml
- lib/flutter_gyw.dart
- lib/src/bt_device.dart
- lib/src/bt_manager.dart
- lib/src/commands.dart
- lib/src/drawings.dart
- lib/src/exceptions.dart
- lib/src/fonts.dart
- lib/src/helpers.dart
- lib/src/icons.dart
- lib/src/screen.dart
- pubspec.yaml
* Upgrade the lints based on Flutter packages lints
* Add a Github action to automatically run tests and lints
* Improve inline documentation seeing the result of `public_member_api_docs`.
The `public_member_api_docs` lint is not active yet, because every constructor and enum value must be documented.
> Improve code documentation

- CHANGELOG.md
- lib/src/drawings.dart
Before this change, the deserialization threw an exception if the scale was an integer and not a double. Now it can be any of those.
> Serialize icon scale also from integers, not only doubles

- CHANGELOG.md
- README.md
- lib/flutter_gyw.dart
- lib/src/commands.dart
- lib/src/drawings.dart
- lib/src/helpers.dart
The new drawing is `RectangleDrawing` which allows for drawing colored rectangles. If the color is null, the rectangle will use the current background color which can be used to partially clear the screen.
A list with a short description of every drawing that can be sent has been added to the documentation.
> Add a new drawing for colored rectangles which allows for partially clearing the screen

- CHANGELOG.md
- assets/icons/blank.svg
blank.svg was not rendering at all in Flutter and was completely transparent before this fix.
> Fix blank.svg not rendering

- CHANGELOG.md
- lib/src/bt_manager.dart
Don't manually query the state of bluetooth because the stream already returns the current value when first listened to.
> Fix bluetooth not enabled error when it's actually enabled

- CHANGELOG.md
- lib/src/drawings.dart
- lib/src/helpers.dart
For simplicity, all fields that were previously of type `num` are now of type `double`.
> Change field types from num to double

- CHANGELOG.md
- lib/src/drawings.dart
WhiteScreen is no longer exported, so instead of returning an instance of WhiteScreen that API users cannot check for, it is now automatically converted into a BlankScreen on deserialization.
> Convert legacy WhiteScreen into BlankScreen

- CHANGELOG.md
- lib/src/drawings.dart
Before this fix, custom icons couldn't have an extension because the library automatically appended `.bin` at the end.
Now, the filename of a custom icon is preserved and sent as is to the firmware.
> Fix custom icon filenames not constructed properly

- CHANGELOG.md
- lib/src/drawings.dart
Rectangles and Spinners were positioned with two integers (`left`, `top`) that were encoded with 2 bytes each. This was not consistent with the position of other drawing elements, where these two integers were encoded on 4 bytes.
> Fix position encoding for rectangles and spinners

- lib/src/drawings.dart
Apparently I didn't properly test #51 and I inverted the red and alpha channel. It should be ARGB, not RGBA.
> Fix 4-byte color strings not converted correctly into commands

- CHANGELOG.md
- analysis_options.yaml
- example/example.dart
- lib/src/bt_device.dart
- lib/src/drawings.dart
- lib/src/icons.dart
- test/drawing_test.dart
Removed:
- `GYWBtDevice.displayDrawing` which was replaced with `GYWBtDevice.sendDrawing`.
- The `WhiteScreen` class.
- Command delays.
- `GYWIcon.path`. Use `GYWIcon.pathPng` or `GYWIcon.pathSvg` instead.
> Remove deprecated functionality

- CHANGELOG.md
- example/example.dart
- lib/flutter_gyw.dart
- lib/src/drawings.dart
- lib/src/fonts.dart
- lib/src/icons.dart
- test/drawing_test.dart
Add support for custom icons and fonts. Enums cannot hold non-constant values, so `GYWIcon` and `GYWFont` are converted into classes, and enums `GYWIcons` and `GYWFonts` contain instances of icons and fonts supported by the device by default.
> Convert GYWIcon and GYWFont from enums to classes

- CHANGELOG.md
- lib/src/drawings.dart
Most colors were previously encoded as 8 or 4 hex characters. They are are now all encoded as RGBA8888.
> Encode all colors in RGBA8888 when sending them to the glasses

- CHANGELOG.md
- lib/src/commands.dart
Some UUIDs have changed because they were reserved by the Bluetooth SIG which we shouldn't have used.
> Update UUIDs of BLE characteristics

- .gitattributes
- CHANGELOG.md
- lib/src/custom_mappers.dart
- lib/src/drawings.dart
- lib/src/drawings.mapper.dart
- lib/src/fonts.dart
- lib/src/icons.dart
- pubspec.yaml
- test/drawing_test.dart
- The [dart_mappable](https://pub.dev/packages/dart_mappable) library has been integrated for the following benefits:
- Generate the serialization and deserialization code which replaces our own `fromJson`/`toJson` methods.
- Automatic generation of `toString`, `hashCode`, `operator ==`, and `copyWith`.
- `GYWDrawing` is now a sealed class, which allows pattern matching to be exhaustive.
> Replace manual serialization code with dart_mappable

- CHANGELOG.md
- lib/src/bt_device.dart
Recent Bluetooth optimizations made to the firmware have added support for writing without response, which enables faster and more flexible device interactions. The API will now always prefer this type of write in all Bluetooth communications.
> Write to Bluetooth characteristics without waiting for a response

- CHANGELOG.md
- README.md
- example/example.dart
- lib/src/bt_device.dart
- lib/src/commands.dart
The screen gets powered on automatically, so `startDisplay` is no longer necessary.
> Remove the `startDisplay` method

- CHANGELOG.md
- README.md
- lib/src/bt_device.dart
- lib/src/commands.dart
- pubspec.yaml
Some features are seen as advanced and quite technical. They are usually not needed to use the glasses. In order to keep a simple and easily maintainable library, these have been removed from the library.
Those methods include:
* `setBrightness`, `setContrast`
* `enableBacklight`, `autoRotateScreen`
The version has also been bumped to 2.0.2 and the package dependencies have been upgraded.
> Remove some technical features that are not needed in the library

- CHANGELOG.md
- lib/src/bt_manager.dart
- lib/src/drawings.dart
- lib/src/helpers.dart
- lib/src/icons.dart
* `.svg` was added to any `GYWIcon` filename, which prevent the use of the object for custom icons, i.e. images that are sent to a single device with the `sendFile` operation. This is now fixed by turning `pathPng` and `pathSvg` into getters.
* The UTF8 encoding operations have been standardized in a `textBytes` method
* The log level of Flutter Bluetooth library has been reduced to Info to reduce the number of log messages
> Fix the use of images that are not library icons
